"""
services/pdf_report_service.py
==============================
Generates print-ready PDF reports for the AthGad AI Admin Workspace
using ReportLab. All data is fetched live from the database / analytics
engine at generation time.

Supported reports:
  - predicted_calamities   : Predicted calamity + mitigation actions per county + date/time
  - disease_outbreaks      : Predicted disease outbreaks per county + preventive measures
  - subscribed_members     : Subscribed member names + subscription date & time
  - unsubscribed_members   : Unsubscribed members + reasons + subscription period
"""

import io
from datetime import datetime
from zoneinfo import ZoneInfo

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.graphics.shapes import Drawing, Circle, Path
from reportlab.graphics import renderPDF

from core.admin_reports import (
    get_predicted_calamities,
    get_disease_outbreaks,
    get_subscribed_members,
    get_unsubscribed_members,
)


def _eat_now():
    """Current time in East Africa Time (UTC+3) for report timestamps."""
    try:
        return datetime.now(tz=ZoneInfo("Africa/Nairobi"))
    except Exception:
        return datetime.now()


# ---- Colour palette (matches the app's dark emerald theme) ----
PRIMARY = colors.HexColor("#0f172a")
ACCENT = colors.HexColor("#10b981")
HEADER_BG = colors.HexColor("#0f172a")
ROW_ALT = colors.HexColor("#f1f5f9")
BORDER = colors.HexColor("#cbd5e1")
TEXT_DARK = colors.HexColor("#0f172a")
TEXT_MUTED = colors.HexColor("#475569")


def _styles():
    s = getSampleStyleSheet()
    styles = {
        "brand": ParagraphStyle(
            "BrandX", parent=s["Normal"], textColor=PRIMARY,
            fontSize=20, fontName="Helvetica-Bold",
            alignment=TA_CENTER, spaceAfter=2, leading=22,
        ),
        "slogan": ParagraphStyle(
            "SloganX", parent=s["Normal"], textColor=ACCENT,
            fontSize=9, fontName="Helvetica",
            alignment=TA_CENTER, spaceAfter=4,
        ),
        "subtitle": ParagraphStyle(
            "SubtitleX", parent=s["Normal"], textColor=ACCENT,
            fontSize=10, alignment=TA_CENTER, spaceAfter=6,
        ),
        "meta": ParagraphStyle(
            "MetaX", parent=s["Normal"], textColor=TEXT_MUTED,
            fontSize=8, alignment=TA_CENTER, spaceAfter=4,
        ),
        "h2": ParagraphStyle(
            "H2X", parent=s["Heading2"], textColor=PRIMARY,
            fontSize=12, spaceBefore=10, spaceAfter=4,
        ),
        "h3": ParagraphStyle(
            "H3X", parent=s["Heading3"], textColor=TEXT_DARK,
            fontSize=9.5, spaceBefore=6, spaceAfter=2,
        ),
        "body": ParagraphStyle(
            "BodyX", parent=s["Normal"], fontSize=8.5,
            leading=11, textColor=TEXT_DARK,
        ),
        "bullet": ParagraphStyle(
            "BulletX", parent=s["Normal"], fontSize=8,
            leading=10.5, leftIndent=10, bulletIndent=2,
            textColor=TEXT_DARK,
        ),
    }
    return styles


def _page_decorator(canvas, doc, report_title):
    """Draws a consistent header/footer on every PDF page."""
    canvas.saveState()
    # Header band
    canvas.setFillColor(PRIMARY)
    canvas.rect(0, doc.height + 34 * mm - 6 * mm, doc.width, 6 * mm, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 9)
    canvas.drawString(16 * mm, doc.height + 36 * mm, "AthGad AI")
    canvas.setFont("Helvetica", 7.5)
    canvas.drawRightString(
        doc.width + 16 * mm, doc.height + 36 * mm,
        report_title,
    )
    # Footer
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(16 * mm, 12 * mm, doc.width + 2 * mm, 12 * mm)
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(
        16 * mm, 8 * mm,
        f"Generated by AthGad AI on {_eat_now().strftime('%Y-%m-%d %H:%M')}",
    )
    canvas.drawRightString(
        doc.width + 16 * mm, 8 * mm,
        f"Page {doc.page}",
    )
    canvas.restoreState()


def _table(headers, rows, col_widths=None):
    """Builds a styled Platypus table."""
    data = [headers] + [list(r) for r in rows]
    tbl = Table(data, colWidths=col_widths, repeatRows=1)
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 7.5),
        ("TEXTCOLOR", (0, 1), (-1, -1), TEXT_DARK),
        ("BACKGROUND", (0, 1), (-1, -1), colors.white),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, ROW_ALT]),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
        ("ALIGN", (0, 0), (-1, 0), "LEFT"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ALIGN", (0, 0), (0, -1), "CENTER"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return tbl


def _mitigation_actions(actions):
    """Returns bulleted paragraphs for a list of mitigation/preventive actions."""
    fragments = []
    for a in actions:
        fragments.append(Paragraph(f"\u2022 {a}", _styles()["bullet"]))
    if not fragments:
        fragments.append(Paragraph("No actions recorded.", _styles()["body"]))
    return fragments


def _athgad_logo(width=18 * mm, height=18 * mm):
    """
    Builds a ReportLab vector drawing of the AthGad AI "sentinel shield" logo.
    Drawn programmatically so no external image asset is required.
    """
    cx, cy = width / 2.0, height / 2.0
    r_outer = min(width, height) * 0.46
    r_inner = r_outer * 0.70
    d = Drawing(width, height)

    # Outer shield path
    shield = Path()
    shield.moveTo(cx, cy + r_outer)
    shield.curveTo(cx + r_outer * 1.15, cy + r_outer * 0.40, cx + r_outer * 0.80, cy - r_outer * 0.9, cx, cy - r_outer)
    shield.curveTo(cx - r_outer * 0.80, cy - r_outer * 0.9, cx - r_outer * 1.15, cy + r_outer * 0.40, cx, cy + r_outer)
    shield.closePath()
    shield.fillColor = ACCENT
    shield.fillMode = 1
    shield.strokeColor = ACCENT
    shield.strokeWidth = 0
    d.add(shield)

    # Inner telemetry ring
    d.add(Circle(cx, cy, r_inner, fillColor=None, strokeColor=colors.HexColor("#0f172a"), strokeWidth=1.2))

    # Central core
    d.add(Circle(cx, cy, r_inner * 0.55, fillColor=colors.HexColor("#38BDF8"), strokeColor=None))

    # Central dot
    d.add(Circle(cx, cy, r_inner * 0.22, fillColor=colors.white, strokeColor=None))

    # Orbital dotted ring
    orb = Circle(cx, cy, r_outer * 0.98, fillColor=None, strokeColor=colors.HexColor("#2563EB"), strokeWidth=0.9)
    orb.strokeDashArray = (1.2, 2.4)
    d.add(orb)

    return d


def _predicted_calamities_pdf(doc, styles, engine):
    items = get_predicted_calamities(engine)
    doc.append(Paragraph("Predicted Calamities & Mitigation Actions", styles["h2"]))
    doc.append(Paragraph(
        "System-predicted calamities for covered counties, the mitigation "
        "actions recommended for each, and the date/time each prediction was produced.",
        styles["body"],
    ))
    doc.append(Spacer(1, 6))

    if not items:
        doc.append(Paragraph(
            "No processed risk data is available yet. Once the system computes "
            "composite risk scores for the covered counties, they will appear here.",
            styles["body"],
        ))
        doc.append(Spacer(1, 6))
        return

    for item in items:
        doc.append(Paragraph(f"{item['county']} County", styles["h3"]))
        doc.append(Paragraph(
            f"<b>Predicted Calamity:</b> {item['calamity_type']} &nbsp;|&nbsp; "
            f"<b>Risk Level:</b> {item['risk_level']} "
            f"&nbsp;|&nbsp; <b>Score:</b> {item['score_pct']}%",
            styles["body"],
        ))
        doc.append(Paragraph(f"<b>Predicted At:</b> {item['predicted_at']}", styles["body"]))
        doc.append(Paragraph("<b>Mitigation Actions:</b>", styles["bullet"]))
        for act in _mitigation_actions(item["mitigation_actions"]):
            doc.append(act)
        doc.append(Spacer(1, 6))


def _disease_outbreaks_pdf(doc, styles, engine):
    items = get_disease_outbreaks(engine)
    doc.append(Paragraph("Predicted Disease Outbreaks & Preventive Measures", styles["h2"]))
    doc.append(Paragraph(
        "Predicted disease outbreaks for covered counties together with the "
        "recommended preventive (mitigation) measures.",
        styles["body"],
    ))
    doc.append(Spacer(1, 6))

    rows = []
    for item in items:
        disease_text = "; ".join(
            f"{d['disease_type']} ({d['reported_cases']} cases)" for d in item["diseases"]
        ) or "No reported cases"
        rows.append([item["county"], disease_text])

    doc.append(_table(["County", "Predicted Disease Outbreaks"], rows))
    doc.append(Spacer(1, 8))

    for item in items:
        doc.append(Paragraph(f"{item['county']} County — Preventive Measures", styles["h3"]))
        for act in _mitigation_actions(item["preventive_measures"]):
            doc.append(act)
    doc.append(Spacer(1, 6))


def _subscribed_members_pdf(doc, styles, engine):
    members = get_subscribed_members(engine)
    doc.append(Paragraph("Subscribed Members", styles["h2"]))
    doc.append(Paragraph(
        "Currently subscribed members with their names and subscription date/time.",
        styles["body"],
    ))
    doc.append(Spacer(1, 6))

    rows = [
        [i + 1, m["full_name"], m["subscribed_at"]]
        for i, m in enumerate(members)
    ]
    if not rows:
        rows = [["1", "No subscribed members", "—"]]

    doc.append(_table(
        ["No.", "Full Name", "Subscribed At"],
        rows,
        col_widths=[12 * mm, 70 * mm, 55 * mm],
    ))
    doc.append(Spacer(1, 8))
    doc.append(Paragraph(f"<b>Total Subscribed Members:</b> {len(members)}", styles["body"]))


def _unsubscribed_members_pdf(doc, styles, engine):
    members = get_unsubscribed_members(engine)
    doc.append(Paragraph("Unsubscribed Members & Unsubscription Reasons", styles["h2"]))
    doc.append(Paragraph(
        "Members who unsubscribed with their reasons, unsubscription date/time, and "
        "the period they were subscribed (in days, weeks, months, or years).",
        styles["body"],
    ))
    doc.append(Spacer(1, 6))

    rows = [
        [
            i + 1,
            m["full_name"],
            m["subscription_period"],
            m["unsubscribed_at"],
            m["channel"],
            m["reason"][:80],
        ]
        for i, m in enumerate(members)
    ]
    if not rows:
        rows = [["1", "No unsubscribed members", "—", "—", "—", "—"]]

    doc.append(_table(
        ["No.", "Full Name", "Period", "Unsubscribed At", "Channel", "Reason"],
        rows,
        col_widths=[10 * mm, 38 * mm, 28 * mm, 35 * mm, 16 * mm, 50 * mm],
    ))
    doc.append(Spacer(1, 8))
    doc.append(Paragraph(f"<b>Total Unsubscribed Members:</b> {len(members)}", styles["body"]))


_BUILDERS = {
    "predicted_calamities": _predicted_calamities_pdf,
    "disease_outbreaks": _disease_outbreaks_pdf,
    "subscribed_members": _subscribed_members_pdf,
    "unsubscribed_members": _unsubscribed_members_pdf,
}

_TITLES = {
    "predicted_calamities": "Predicted Calamities Report",
    "disease_outbreaks": "Disease Outbreaks Report",
    "subscribed_members": "Subscribed Members Report",
    "unsubscribed_members": "Unsubscribed Members Report",
}


def build_admin_report(engine, report_type: str) -> bytes:
    """
    Builds the requested admin PDF report and returns it as bytes.

    Args:
        engine: SQLAlchemy engine (passed through to the data-access layer).
        report_type: one of the keys in _BUILDERS.

    Returns:
        PDF file contents as bytes.
    """
    if report_type not in _BUILDERS:
        raise ValueError(f"Unknown report type: {report_type}")

    title = _TITLES[report_type]
    buf = io.BytesIO()

    # A4 with consistent margins; use large enough left/right for the header text.
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=16 * mm,
        rightMargin=16 * mm,
        topMargin=38 * mm,
        bottomMargin=18 * mm,
        title=title,
        author="AthGad AI",
    )

    styles = _styles()
    story = []

    # ── Centred brand header: logo + name + slogan ──
    logo = _athgad_logo(22 * mm, 22 * mm)
    logo.hAlign = "CENTER"
    story.append(logo)
    story.append(Spacer(1, 4))
    story.append(Paragraph("AthGad AI", styles["brand"]))
    story.append(Paragraph(
        "AI-Powered Early Warning System for Eastern Kenya",
        styles["slogan"],
    ))
    story.append(Spacer(1, 6))
    story.append(Paragraph(f"ADMIN REPORT — {title.upper()}", styles["subtitle"]))
    story.append(Paragraph(
        f"Eastern Kenya Early Warning System | "
        f"Generated: {_eat_now().strftime('%Y-%m-%d %H:%M')}",
        styles["meta"],
    ))
    story.append(Spacer(1, 8))

    # Dispatch to the correct report builder
    _BUILDERS[report_type](story, styles, engine)

    doc.build(
        story,
        onFirstPage=lambda c, d: _page_decorator(c, d, title),
        onLaterPages=lambda c, d: _page_decorator(c, d, title),
    )

    return buf.getvalue()
